"""Create a visual-fidelity Word wrapper for a PDF.

Each source page is rendered as one high-resolution image on a matching Word
page.  This is intentionally a viewing/printing artifact; the editable text
DOCX generated by pdf_office_export remains the file used by the engine.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt


def build_visual_docx(pdf_path: str | Path, output: str | Path, dpi: int = 144) -> dict[str, Any]:
    source = Path(pdf_path)
    destination = Path(output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        import pymupdf as fitz  # type: ignore
    except ImportError:
        import fitz  # type: ignore

    document = Document()
    first = document.sections[0]
    first.top_margin = Inches(0.55)
    first.bottom_margin = Inches(0.55)
    first.left_margin = Inches(0.55)
    first.right_margin = Inches(0.55)
    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run(f"{source.stem} PDF 版式保真查看版").bold = True
    intro = document.add_paragraph(
        "本文件按 PDF 页面渲染，保留原始排版、表格和图表视觉效果。"
        "它用于查看和打印；需要被知链识别、关联和修改时，请使用同文件夹中的可编辑正文 Word。"
    )
    intro.paragraph_format.space_after = Pt(8)
    with fitz.open(str(source)) as pdf:
        pages = pdf.page_count
        for index, page in enumerate(pdf):
            section = document.add_section(WD_SECTION.NEW_PAGE)
            width = max(float(page.rect.width) / 72.0, 2.0)
            height = max(float(page.rect.height) / 72.0, 2.0)
            section.page_width = Inches(width)
            section.page_height = Inches(height)
            margin = 18 / 72.0
            section.top_margin = Inches(margin)
            section.bottom_margin = Inches(margin)
            section.left_margin = Inches(margin)
            section.right_margin = Inches(margin)
            section.header_distance = Inches(5 / 72.0)
            section.footer_distance = Inches(5 / 72.0)
            paragraph = document.add_paragraph()
            paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            paragraph.paragraph_format.space_before = Pt(0)
            paragraph.paragraph_format.space_after = Pt(0)
            pix = page.get_pixmap(matrix=fitz.Matrix(dpi / 72.0, dpi / 72.0), alpha=False)
            image_path = destination.parent / f".pdf_page_{index + 1:04d}.png"
            pix.save(str(image_path))
            paragraph.add_run().add_picture(str(image_path), width=Inches(width - 2 * margin))
            image_path.unlink(missing_ok=True)
    document.save(destination)
    return {"pages": pages, "output": str(destination), "editable": False, "dpi": dpi}


__all__ = ["build_visual_docx"]
