"""Materialise a PDF into editable Word and Excel source artifacts.

This is the supported PDF product path.  It never edits the input PDF.  The
text layer becomes a page-labelled DOCX evidence document and validated table
rows become an XLSX fact-source candidate with provenance columns.  Charts and
failed rows remain review records rather than guessed data.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_SECTION
from docx.oxml.ns import qn
from docx.shared import Inches, Pt

from .pdf_ingest import extract_pdf
from .engine import extract_claims


FACT_HEADERS = ["事实ID", "主体", "指标", "期间", "数值", "单位", "统计口径"]
PROVENANCE_HEADERS = ["来源文件", "来源页", "表格编号", "表格行", "提取状态", "独立交叉校验", "校验状态"]


def _safe_name(name: str) -> str:
    value = re.sub(r"[<>:\"/\\|?*\x00-\x1f]", "_", name).strip(" .")
    return value or "pdf_import"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _pdf_text_pages(path: Path) -> list[dict[str, Any]]:
    try:
        import pymupdf as fitz  # type: ignore
    except ImportError:
        import fitz  # type: ignore
    with fitz.open(str(path)) as document:
        pages = []
        for index, page in enumerate(document, 1):
            # Keep the plain text fallback for compatibility, but also retain
            # line coordinates and span sizes.  A PDF is positioned text, so
            # throwing these coordinates away creates a dense, unreadable
            # Word document even when extraction itself is correct.
            layout = []
            for block in page.get_text("dict", sort=True).get("blocks", []):
                if block.get("type") != 0:
                    continue
                lines = []
                for line in block.get("lines", []):
                    spans = []
                    for span in line.get("spans", []):
                        text = span.get("text", "")
                        if not text:
                            continue
                        spans.append({
                            "text": text,
                            "size": float(span.get("size") or 9),
                            "font": span.get("font") or "Microsoft YaHei",
                            "flags": int(span.get("flags") or 0),
                        })
                    if spans:
                        lines.append({"bbox": tuple(line.get("bbox") or block.get("bbox")), "spans": spans})
                if lines:
                    layout.append({"bbox": tuple(block.get("bbox")), "lines": lines})
            pages.append({
                "page": index,
                "text": page.get_text("text", sort=True) or "",
                "width": float(page.rect.width),
                "height": float(page.rect.height),
                "blocks": layout,
            })
        return pages


def _text_anchors(text_pages: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Flatten PDF text blocks into stable page/coordinate evidence anchors.

    The editable Word is a reconstruction and may reflow.  These anchors keep
    later claim verification tied to the original PDF text layer instead of to
    text generated by our own DOCX exporter.
    """
    anchors: list[dict[str, Any]] = []
    for page_item in text_pages:
        page = int(page_item.get("page") or 0)
        # Compatibility fallback for callers that provide only plain text.
        if not page_item.get("blocks") and str(page_item.get("text") or "").strip():
            anchors.append({
                "id": f"pdf-p{page}-text",
                "page": page,
                "bbox": [],
                "text": str(page_item.get("text") or ""),
                "source": "pdf_text_layer",
            })
            continue
        for block_index, block in enumerate(page_item.get("blocks") or [], 1):
            for line_index, line in enumerate(block.get("lines") or [], 1):
                spans = line.get("spans") or []
                text = "".join(str(span.get("text") or "") for span in spans)
                if not text.strip():
                    continue
                bbox = list(line.get("bbox") or block.get("bbox") or [])
                anchors.append({
                    "id": f"pdf-p{page}-b{block_index}-l{line_index}",
                    "page": page,
                    "bbox": [round(float(value), 3) for value in bbox],
                    "text": text,
                    "source": "pdf_text_layer",
                })
    return anchors


def _build_claim_candidates(text_pages: list[dict[str, Any]], source_file: str) -> list[dict[str, Any]]:
    """Index deterministic claim candidates against original PDF pages.

    This is deliberately a candidate index, not an accepted truth set. It
    gives the agent a semantic starting point while preserving the original
    page and text anchor needed for later review.
    """
    candidates: list[dict[str, Any]] = []
    for page_item in text_pages:
        page = int(page_item.get("page") or 0)
        text = str(page_item.get("text") or "")
        for sentence_index, sentence_match in enumerate(re.finditer(r"[^。！？；;\n]+", text)):
            sentence = sentence_match.group().strip()
            if not sentence or not re.search(r"\d", sentence):
                continue
            block = {"file_id": source_file, "location": ["pdf", page, sentence_index],
                     "label": f"PDF 第 {page} 页", "text": sentence}
            for claim in extract_claims(block, []):
                item = dict(claim)
                item.update({"source_pdf": source_file, "pdf_page": page,
                             "sentence_index": sentence_index,
                             "source": "pdf_text_layer", "review_status": "待确认"})
                candidates.append(item)
    return candidates


def _set_doc_defaults(document: Document) -> None:
    section = document.sections[0]
    section.top_margin = Inches(0.7)
    section.bottom_margin = Inches(0.7)
    section.left_margin = Inches(0.8)
    section.right_margin = Inches(0.8)
    styles = document.styles
    styles["Normal"].font.name = "Microsoft YaHei"
    styles["Normal"]._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    styles["Normal"].font.size = Pt(10.5)
    for style_name in ("Title", "Heading 1", "Heading 2"):
        style = styles[style_name]
        style.font.name = "Microsoft YaHei"
        style._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        style.font.color.rgb = None
        ppr = style._element.get_or_add_pPr()
        for child in list(ppr):
            if child.tag == qn("w:pBdr"):
                ppr.remove(child)


def _set_page_section(section, item: dict[str, Any]) -> float:
    """Match the Word section to the source PDF page and return margin points."""
    width = max(float(item.get("width") or 595.35), 144.0)
    height = max(float(item.get("height") or 841.95), 144.0)
    margin = 10.0  # narrow margin preserves the source page's usable area
    section.page_width = Inches(width / 72.0)
    section.page_height = Inches(height / 72.0)
    section.top_margin = Inches(margin / 72.0)
    section.bottom_margin = Inches(margin / 72.0)
    section.left_margin = Inches(margin / 72.0)
    section.right_margin = Inches(margin / 72.0)
    section.header_distance = Inches(8 / 72.0)
    section.footer_distance = Inches(8 / 72.0)
    return margin


def _set_page_header(section, page_number: int) -> None:
    section.header.is_linked_to_previous = False
    header = section.header.paragraphs[0]
    header.text = ""
    header.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = header.add_run(f"第 {page_number} 页 · PDF 正文提取")
    run.font.name = "Microsoft YaHei"
    run._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    run.font.size = Pt(7)
    run.font.color.rgb = None


def _add_layout_line(document: Document, line: dict[str, Any], margin: float, previous_bottom: float | None) -> float:
    segments = line.get("segments") or [line]
    boxes = [segment.get("bbox") or (0, 0, 0, 0) for segment in segments]
    x0 = min(float(box[0]) for box in boxes)
    y0 = min(float(box[1]) for box in boxes)
    y1 = max(float(box[3]) for box in boxes)
    paragraph = document.add_paragraph()
    fmt = paragraph.paragraph_format
    fmt.left_indent = Inches(max(0.0, x0 - margin) / 72.0)
    gap = max(0.0, y0 - (previous_bottom if previous_bottom is not None else margin))
    # Preserve vertical gaps between PDF lines, but cap pathological gaps from
    # page furniture so the result remains editable and does not create blank
    # pages in Word.
    fmt.space_before = Pt(min(gap, 72.0))
    fmt.space_after = Pt(0)
    all_spans = [span for segment in segments for span in segment.get("spans", [])]
    sizes = [float(span.get("size") or 9) for span in all_spans]
    size = max(6.0, min(max(sizes, default=9.0), 32.0))
    # Use the extracted glyph box for exact line height.  A fixed 1.08× font
    # leading accumulates a few points on every line and pushes dense source
    # pages onto an unintended second Word page.
    line_height = max(6.0, min(48.0, max(y1 - y0, size * 0.95)))
    fmt.line_spacing = Pt(line_height)
    fmt.keep_together = False
    first_x = x0
    for segment_index, segment in enumerate(segments):
        segment_x = float((segment.get("bbox") or (first_x, 0, 0, 0))[0])
        if segment_index:
            # A single PDF baseline can contain several table columns.  Keep
            # them in one Word paragraph and use explicit tab stops so each
            # column does not consume another line of vertical space.
            fmt.tab_stops.add_tab_stop(Inches(max(0.0, segment_x - first_x) / 72.0))
            paragraph.add_run("\t")
        for span in segment.get("spans", []):
            run = paragraph.add_run(span.get("text", ""))
            font_name = span.get("font") or "Microsoft YaHei"
            run.font.name = font_name
            run._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:eastAsia"), font_name)
            run.font.size = Pt(max(6.0, min(float(span.get("size") or size), 32.0)))
            # PDF font flags use bit 16 for bold in common producers.
            if int(span.get("flags") or 0) & 16:
                run.bold = True
    return max(previous_bottom or 0.0, y1)


def _build_docx(pdf_path: Path, text_pages: list[dict[str, Any]], output: Path) -> None:
    document = Document()
    _set_doc_defaults(document)
    title = document.add_paragraph(style="Title")
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run(f"{pdf_path.stem} PDF 正文提取")
    intro = document.add_paragraph()
    intro.add_run("用途：").bold = True
    intro.add_run("本文件由知链从 PDF 文字层生成，用作可编辑的论断来源。原 PDF 未被修改。每页标题保留原始页码，正文内容按文字层顺序写入。")
    source = document.add_paragraph()
    source.add_run("来源文件：").bold = True
    source.add_run(pdf_path.name)
    source.add_run(f"；SHA-256：{_sha256(pdf_path)}")

    for page_index, item in enumerate(text_pages):
        section = document.add_section(WD_SECTION.NEW_PAGE)
        margin = _set_page_section(section, item)
        _set_page_header(section, int(item.get("page") or page_index + 1))
        blocks = item.get("blocks") or []
        lines = [line for block in blocks for line in block.get("lines", [])]
        # A PDF table is often stored as many independent text blocks.  The
        # producer's block order is not guaranteed to be globally top-to-bottom
        # (especially across columns), so sort by the visible baseline before
        # reconstructing Word paragraphs; otherwise artificial vertical gaps
        # can make one source page spill onto two Word pages.
        lines.sort(key=lambda line: ((line.get("bbox") or (0, 0))[1], (line.get("bbox") or (0, 0))[0]))
        grouped_lines = []
        for line in lines:
            y0 = float((line.get("bbox") or (0, 0))[1])
            if grouped_lines and abs(y0 - grouped_lines[-1]["y0"]) <= 1.5:
                grouped_lines[-1]["segments"].append(line)
                grouped_lines[-1]["y0"] = min(grouped_lines[-1]["y0"], y0)
            else:
                grouped_lines.append({"y0": y0, "segments": [line]})
        if lines:
            previous_bottom = None
            for group in grouped_lines:
                previous_bottom = _add_layout_line(document, group, margin, previous_bottom)
            continue
        text = item.get("text", "").strip()
        if not text:
            paragraph = document.add_paragraph("（本页没有可提取文字层，可能是扫描页或纯图页。）")
            paragraph.runs[0].italic = True
            continue
        # Compatibility fallback for callers/tests that provide only plain text.
        for line in text.splitlines():
            line = line.strip()
            if line:
                paragraph = document.add_paragraph(line)
                paragraph.paragraph_format.space_after = Pt(0)

    section = document.sections[-1]
    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run("知链 PDF 正文提取稿 · 原始页码见各节标题")
    document.save(output)


def _style_sheet(sheet, freeze="A2") -> None:
    sheet.freeze_panes = freeze
    sheet.auto_filter.ref = sheet.dimensions
    header_fill = PatternFill("solid", fgColor="1F4E78")
    for cell in sheet[1]:
        cell.fill = header_fill
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for row in sheet.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(vertical="top", wrap_text=True)
    for index, column_cells in enumerate(sheet.columns, 1):
        values = [str(cell.value or "") for cell in column_cells[:100]]
        width = min(max(max((len(value) for value in values), default=8) + 2, 10), 42)
        sheet.column_dimensions[get_column_letter(index)].width = width


def _build_xlsx(pdf_path: Path, result: dict[str, Any], output: Path, subject: str | None) -> None:
    workbook = Workbook()
    facts_sheet = workbook.active
    facts_sheet.title = "事实候选"
    headers = FACT_HEADERS + PROVENANCE_HEADERS
    facts_sheet.append(headers)
    subject_value = subject or pdf_path.stem
    for fact in result.get("facts", []):
        if fact.get("unit") in {None, "", "表内单位"}:
            extraction_status = "待复核：单位未识别"
        elif fact.get("cross_check_status") != "passed":
            extraction_status = "待复核：缺少独立交叉校验"
        else:
            extraction_status = "待复核：交叉校验通过"
        facts_sheet.append([
            fact.get("id", ""), subject_value, fact.get("metric", ""), fact.get("period", ""),
            fact.get("value"), fact.get("unit", ""), fact.get("scope", ""),
            fact.get("source_file", pdf_path.name), fact.get("source_page"),
            fact.get("source_table"), fact.get("source_row"), extraction_status,
            "是" if fact.get("has_cross_check") else "否", fact.get("cross_check_status", "not_available"),
        ])
    _style_sheet(facts_sheet)
    facts_sheet.sheet_view.showGridLines = False

    conflicts_sheet = workbook.create_sheet("冲突待复核")
    conflicts_sheet.append(["来源页", "指标", "期间", "候选值", "单位", "表格编号", "行号", "隔离原因"])
    for conflict in result.get("fact_conflicts", []):
        for candidate in conflict.get("candidates", []):
            conflicts_sheet.append([
                conflict.get("source_page"), conflict.get("metric"), conflict.get("period"),
                candidate.get("value"), candidate.get("unit"), candidate.get("source_table"),
                candidate.get("source_row"), conflict.get("reason"),
            ])
    _style_sheet(conflicts_sheet)
    conflicts_sheet.sheet_view.showGridLines = False

    checks_sheet = workbook.create_sheet("表格校验")
    checks_sheet.append(["来源文件", "来源页", "表格编号", "指标", "计算变动", "报告变动", "独立交叉校验", "容差内", "行号"])
    for table in result.get("tables", []):
        validation = table.get("validation") or {}
        for check in validation.get("checks", []):
            checks_sheet.append([
                check.get("source_file", pdf_path.name), check.get("source_page"),
                check.get("table_number", table.get("table")), check.get("metric", ""),
                check.get("calculated_change"), check.get("reported_change"),
                "是" if check.get("has_cross_check") else "否",
                "是" if check.get("within_tolerance") else "否", check.get("row_number"),
            ])
    _style_sheet(checks_sheet)
    checks_sheet.sheet_view.showGridLines = False

    raw_sheet = workbook.create_sheet("表格原文")
    raw_sheet.append(["来源文件", "来源页", "表格编号", "行号", "列号", "原始内容"])
    for table in result.get("tables", []):
        for row_number, row in enumerate(table.get("rows", []), 1):
            for column_number, value in enumerate(row, 1):
                raw_sheet.append([pdf_path.name, table.get("page"), table.get("table"),
                                  row_number, column_number, value])
    _style_sheet(raw_sheet)
    raw_sheet.sheet_view.showGridLines = False

    summary = workbook.create_sheet("转换摘要", 0)
    summary.append(["项目", "值"])
    for key, value in [
        ("原始文件", pdf_path.name),
        ("原始文件 SHA-256", _sha256(pdf_path)),
        ("页数", result.get("pages", 0)),
        ("文字层页数", result.get("text_layer_pages", 0)),
        ("文字层覆盖率", result.get("text_layer_ratio", 0)),
        ("候选表格数", len(result.get("tables", []))),
        ("待确认事实候选数", len(result.get("facts", []))),
        ("冲突隔离组数", len(result.get("fact_conflicts", []))),
        ("图表候选页数", len(result.get("chart_candidates", []))),
        ("事实状态", "待确认；确认后可作为项目事实源"),
        ("图表状态", "仅候选，不自动写入事实数值"),
    ]:
        summary.append([key, value])
    _style_sheet(summary, freeze="A2")
    summary.sheet_view.showGridLines = False

    workbook.save(output)


def export_pdf_to_office(
    pdf_path: str | Path,
    output_dir: str | Path,
    *,
    subject: str | None = None,
    max_pages: int = 500,
    docx_backend: str = "native",
) -> dict[str, Any]:
    """Extract one PDF into a Word text source and Excel fact candidate.

    ``native`` is the deterministic coordinate-aware builder used by the
    product. ``pdf2docx`` is an explicit optional backend for born-digital
    PDFs; its result still requires page-count and visual verification.
    """
    source = Path(pdf_path)
    if source.suffix.lower() != ".pdf":
        raise ValueError("仅支持 PDF 文件")
    if not source.is_file():
        raise FileNotFoundError(source)
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    stem = _safe_name(source.stem)
    result = extract_pdf(source, output_dir=destination / "pdf_evidence", max_pages=max_pages)
    text_pages = _pdf_text_pages(source)
    anchors = _text_anchors(text_pages)
    claim_candidates = _build_claim_candidates(text_pages, source.name)
    word_path = destination / f"{stem}_正文提取.docx"
    excel_path = destination / f"{stem}_事实表候选.xlsx"
    anchors_path = destination / f"{stem}_文字锚点.json"
    claims_path = destination / f"{stem}_论断候选.jsonl"
    manifest_path = destination / f"{stem}_转换清单.json"
    selected_backend = str(docx_backend or "native").strip().lower()
    if selected_backend == "auto":
        from .pdf_revised_export import choose_pdf_docx_backend
        selected_backend = choose_pdf_docx_backend("auto")
    if selected_backend == "native":
        _build_docx(source, text_pages, word_path)
    elif selected_backend == "pdf2docx":
        from .pdf_revised_export import export_pdf_to_editable_docx
        export_pdf_to_editable_docx(source, word_path)
    else:
        raise ValueError("docx_backend 仅支持 native 或 pdf2docx")
    _build_xlsx(source, result, excel_path, subject)
    anchors_path.write_text(json.dumps({
        "source_pdf": source.name,
        "source_sha256": _sha256(source),
        "anchors": anchors,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
    claims_path.write_text(
        "".join(json.dumps(item, ensure_ascii=False) + "\n" for item in claim_candidates),
        encoding="utf-8",
    )
    manifest = {
        "source_pdf": str(source),
        "source_sha256": _sha256(source),
        "word": str(word_path),
        "excel": str(excel_path),
        "text_anchors": str(anchors_path),
        "text_anchor_count": len(anchors),
        "claim_candidates": str(claims_path),
        "claim_candidate_count": len(claim_candidates),
        "facts": len(result.get("facts", [])),
        "tables": len(result.get("tables", [])),
        "chart_candidates": len(result.get("chart_candidates", [])),
        "text_pages": len(text_pages),
        "requires_confirmation": True,
        "original_pdf_modified": False,
        "docx_backend": selected_backend,
        "pdf_revision": {
            "available": False,
            "reason": "需在确认修复 Word 后调用 Word/LibreOffice 导出器生成独立修订版 PDF",
            "original_is_read_only": True,
        },
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    return manifest


__all__ = ["export_pdf_to_office"]
